/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajoGen;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author
 */
public class Tabla extends javax.swing.JFrame {

    Raster raster;
    JPanel Pizarron;
    Point p1, p2, p3, p4, p5, p6, p7, p8;
    boolean b1, b2, b3, b4;
    ArrayList<Figura> arregloF = new ArrayList();
    int contadorlinea = 0, contadorcirculo = 0, contadorelipse = 0, contadortriangulo = 0, contadorcuadrado = 0;
    Matrix matriz = new Matrix();

    /**
     * Creates new form MiniCad
     */
    public Tabla() {
        initComponents();
        p1 = new Point();
        p2 = new Point();
        p3 = new Point();
        p4 = new Point();
        p5 = new Point();
        p6 = new Point();
        p7 = new Point();
        p8 = new Point();
        b1 = b2 = b3 = b4 = true;
        raster = new Raster(800, 400);
        Pizarron = new Panel(raster);
        Pizarron.setSize(new Dimension(400, 400));
        Pizarron.setBackground(Color.BLACK);
        setLayout(new BorderLayout());
        setSize(new Dimension(800, 600));
        setMaximumSize(new Dimension(800, 600));
        setMinimumSize(new Dimension(800, 600));
        getContentPane().setBackground(Color.red);
        setLocationRelativeTo(null);
        jPanel1.setSize(new Dimension(800, 200));
        jPanel1.setMaximumSize(new Dimension(800, 200));
        jPanel1.setMinimumSize(new Dimension(800, 200));
        Pizarron.setMaximumSize(new Dimension(400, 400));
        Pizarron.setMinimumSize(new Dimension(400, 400));
        add(Pizarron, BorderLayout.SOUTH);
        Pizarron.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                PizarraMouseClicked(evt);
            }
        });
        this.revalidate();
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("trabajoGen");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(200, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Formas"));
        jPanel2.setOpaque(false);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton1.setText("Linea");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton2.setText("Circulo");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton4.setText("Triangulo");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton5.setText("Cuadrado");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addGap(95, 95, 95)
                .addComponent(jRadioButton2)
                .addGap(95, 95, 95)
                .addComponent(jRadioButton4)
                .addGap(95, 95, 95)
                .addComponent(jRadioButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Opciones"));
        jPanel3.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Formas:");

        jButton1.setText("Aplicar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton6.setSelected(true);
        jRadioButton6.setText("Traslacion (X,Y)");

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton7.setText("Escala (X,Y)");

        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton8.setText("Rotacion");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jRadioButton6)
                .addGap(34, 34, 34)
                .addComponent(jRadioButton7)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton8)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(84, 84, 84))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gerardo\\Pictures\\ccf7daada1cadeebd49d685d9aff74171505144305_large.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        b1 = b2 = b3 = b4 = true;
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:   
        b1 = b2 = b3 = b4 = true;
    }//GEN-LAST:event_jRadioButton2ActionPerformed
/**/
    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        b1 = b2 = b3 = b4 = true;
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        b1 = b2 = b3 = b4 = true;
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if (this.jRadioButton6.isSelected()) {
                int dato[] = new int[2];
                int index = this.jComboBox1.getSelectedIndex();
                String dat[] = this.jTextField1.getText().split(",");
                dato[0] = Integer.parseInt(dat[0]);
                dato[1] = Integer.parseInt(dat[1]);
                Figura f = this.arregloF.get(index);
                Matrix m = new Matrix();
                m.traslacion(dato[0] * 40, dato[1] * 30 * -1);
                if (f.id != 4) {
                    double pt1[] = new double[3];
                    pt1[0] = f.puntos[0].getX();
                    pt1[1] = f.puntos[0].getY();
                    pt1[2] = 1;
                    pt1 = m.pprima(pt1);
                    double pt2[] = new double[3];
                    pt2[0] = f.puntos[1].getX();
                    pt2[1] = f.puntos[1].getY();
                    pt2[2] = 1;
                    pt2 = m.pprima(pt2);
                    arregloF.get(index).puntos[0].setLocation(pt1[0], pt1[1]);
                    arregloF.get(index).puntos[1].setLocation(pt2[0], pt2[1]);
                } else {
                    double pt1[] = new double[3];
                    double pt2[] = new double[3];
                    double pt3[] = new double[3];
                    pt1[0] = f.puntos[0].getX();
                    pt1[1] = f.puntos[0].getY();
                    pt1[2] = 1;
                    pt1 = m.pprima(pt1);
                    pt2[0] = f.puntos[1].getX();
                    pt2[1] = f.puntos[1].getY();
                    pt2[2] = 1;
                    pt2 = m.pprima(pt2);
                    pt3[0] = f.puntos[2].getX();
                    pt3[1] = f.puntos[2].getY();
                    pt3[2] = 1;
                    pt3 = m.pprima(pt3);
                    arregloF.get(index).puntos[0].setLocation(pt1[0], pt1[1]);
                    arregloF.get(index).puntos[1].setLocation(pt2[0], pt2[1]);
                    arregloF.get(index).puntos[2].setLocation(pt3[0], pt3[1]);
                }
            }
            if (this.jRadioButton8.isSelected()) {
                int index = this.jComboBox1.getSelectedIndex();
                int dato = Integer.parseInt(this.jTextField1.getText());
                Figura f = this.arregloF.get(index);
                Matrix m = new Matrix();
                m.traslacion(-f.puntos[0].x, -f.puntos[0].y);
                m.rotacion(dato * -1);
                m.traslacion(f.puntos[0].x, f.puntos[0].y);
                if (f.id != 4) {
                    double pt1[] = new double[3];
                    pt1[0] = f.puntos[0].getX();
                    pt1[1] = f.puntos[0].getY();
                    pt1[2] = 1;
                    pt1 = m.pprima(pt1);
                    double pt2[] = new double[3];
                    pt2[0] = f.puntos[1].getX();
                    pt2[1] = f.puntos[1].getY();
                    pt2[2] = 1;
                    pt2 = m.pprima(pt2);
                    arregloF.get(index).puntos[0].setLocation(pt1[0], pt1[1]);
                    arregloF.get(index).puntos[1].setLocation(pt2[0], pt2[1]);
                } else {
                    double pt1[] = new double[3];
                    double pt2[] = new double[3];
                    double pt3[] = new double[3];
                    pt1[0] = f.puntos[0].getX();
                    pt1[1] = f.puntos[0].getY();
                    pt1[2] = 1;
                    pt1 = m.pprima(pt1);
                    pt2[0] = f.puntos[1].getX();
                    pt2[1] = f.puntos[1].getY();
                    pt2[2] = 1;
                    pt2 = m.pprima(pt2);
                    pt3[0] = f.puntos[2].getX();
                    pt3[1] = f.puntos[2].getY();
                    pt3[2] = 1;
                    pt3 = m.pprima(pt3);
                    arregloF.get(index).puntos[0].setLocation(pt1[0], pt1[1]);
                    arregloF.get(index).puntos[1].setLocation(pt2[0], pt2[1]);
                    arregloF.get(index).puntos[2].setLocation(pt3[0], pt3[1]);
                }
            }
            if (this.jRadioButton7.isSelected()) {
                double dato[] = new double[2];
                int index = this.jComboBox1.getSelectedIndex();
                String dat[] = this.jTextField1.getText().split(",");
                dato[0] = Double.parseDouble(dat[0]);
                dato[1] = Double.parseDouble(dat[1]);
                Figura f = this.arregloF.get(index);
                Matrix m = new Matrix();
                m.traslacion(-f.puntos[0].x, -f.puntos[0].y);
                m.escalarXY(dato[0], dato[1]);
                m.traslacion(f.puntos[0].x, f.puntos[0].y);
                if (f.id != 4) {
                    double pt1[] = new double[3];
                    pt1[0] = f.puntos[0].getX();
                    pt1[1] = f.puntos[0].getY();
                    pt1[2] = 1;
                    pt1 = m.pprima(pt1);
                    double pt2[] = new double[3];
                    pt2[0] = f.puntos[1].getX();
                    pt2[1] = f.puntos[1].getY();
                    pt2[2] = 1;
                    pt2 = m.pprima(pt2);
                    arregloF.get(index).puntos[0].setLocation(pt1[0], pt1[1]);
                    arregloF.get(index).puntos[1].setLocation(pt2[0], pt2[1]);
                    if (arregloF.get(index).id == 2) {
                        arregloF.get(index).d *= dato[0] * dato[1];
                    }
                } else {
                    double pt1[] = new double[3];
                    double pt2[] = new double[3];
                    double pt3[] = new double[3];
                    pt1[0] = f.puntos[0].getX();
                    pt1[1] = f.puntos[0].getY();
                    pt1[2] = 1;
                    pt1 = m.pprima(pt1);
                    pt2[0] = f.puntos[1].getX();
                    pt2[1] = f.puntos[1].getY();
                    pt2[2] = 1;
                    pt2 = m.pprima(pt2);
                    pt3[0] = f.puntos[2].getX();
                    pt3[1] = f.puntos[2].getY();
                    pt3[2] = 1;
                    pt3 = m.pprima(pt3);
                    arregloF.get(index).puntos[0].setLocation(pt1[0], pt1[1]);
                    arregloF.get(index).puntos[1].setLocation(pt2[0], pt2[1]);
                    arregloF.get(index).puntos[2].setLocation(pt3[0], pt3[1]);
                }
            }

            Reset();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabla().setVisible(true);
            }
        });

    }

    public void Reset() {
        raster.fill(Color.BLACK);
        for (int j = 0; j < arregloF.size(); j++) {
            ReDibujar(arregloF.get(j), arregloF.get(j).color);
        }
    }

    public void ReDibujar(Figura figura, Color color) {
        switch (figura.id) {
            case 1:
                dibujarLinea(figura.puntos[0], figura.puntos[1], color);
                break;
            case 2:
                Circulo(figura.puntos[0], figura.puntos[1], (int) figura.d, color);
                break;
            case 3:
                Elipse(figura.puntos[0], figura.puntos[1],figura.d, color);
                break;
            case 4:
                Triangulo(figura.puntos[0], figura.puntos[1], figura.puntos[2], color);
                break;
            case 5:
                Cuadrado(figura.puntos[0], figura.puntos[1], color);
                break;
            default:
                break;
        }
    }

    public void lineFast(int x0, int y0, int x1, int y1, Color color) {
        int pix = color.getRGB();
        int dy = y1 - y0;
        int dx = x1 - x0;
        int stepx, stepy;
        if (dy < 0) {
            dy = -dy;
            stepy = -raster.width;
        } else {
            stepy = raster.width;
        }
        if (dx < 0) {
            dx = -dx;
            stepx = -1;
        } else {
            stepx = 1;
        }
        dy <<= 1;
        dx <<= 1;
        y0 *= raster.width;
        y1 *= raster.width;
        raster.pixel[x0 + y0] = pix;
        if (dx > dy) {
            int fraction = dy - (dx >> 1);
            while (x0 != x1) {
                if (fraction >= 0) {
                    y0 += stepy;
                    fraction -= dx;
                }
                x0 += stepx;
                fraction += dy;
                raster.pixel[x0 + y0] = pix;
            }
        } else {
            int fraction = dx - (dy >> 1);
            while (y0 != y1) {
                if (fraction >= 0) {
                    x0 += stepx;
                    fraction -= dy;
                }
                y0 += stepy;
                fraction += dx;
                raster.pixel[x0 + y0] = pix;
            }
        }
    }

    public void dibujarLinea(Point _p1, Point _p2, Color color) {
        lineFast(_p1.x, _p1.y, _p2.x, _p2.y, color);
    }

    public void Triangulo(Point p1, Point p2, Point p3, Color c) {
        // TODO add your handling code here:
        Vertex2D v1 = new Vertex2D(p1.x, p1.y, c.getRGB());
        Vertex2D v2 = new Vertex2D(p2.x, p2.y, c.getRGB());
        Vertex2D v3 = new Vertex2D(p3.x, p3.y, c.getRGB());

        TrianguloR tri = new TrianguloR(v1, v2, v3, c);

        tri.dibujar(raster);
    }

    public void Cuadrado(Point p1, Point p2, Color color) {
        int d = (int) (Rad(p2, p1) / Math.sqrt(2));
        if ((p1.x < p2.x) && (p1.y < p2.y)) {
            Vertex2D v1 = new Vertex2D(p1.x, p1.y, color.getRGB());
            Vertex2D v2 = new Vertex2D(p1.x + d, p1.y, color.getRGB());
            Vertex2D v3 = new Vertex2D(p1.x, p1.y + d, color.getRGB());
            Vertex2D v4 = new Vertex2D(p2.x, p2.y, color.getRGB());
            TrianguloR tri = new TrianguloR(v1, v2, v3, color);
            tri.dibujar(raster);
            TrianguloR tri2 = new TrianguloR(v2, v3, v4, color);
            tri2.dibujar(raster);
        } else if ((p1.x < p2.x) && (p1.y > p2.y)) {
            Vertex2D v1 = new Vertex2D(p1.x, p1.y, color.getRGB());
            Vertex2D v2 = new Vertex2D(p1.x + d, p1.y, color.getRGB());
            Vertex2D v3 = new Vertex2D(p1.x, p1.y - d, color.getRGB());
            Vertex2D v4 = new Vertex2D(p2.x, p2.y, color.getRGB());
            TrianguloR tri = new TrianguloR(v1, v2, v3, color);
            tri.dibujar(raster);
            TrianguloR tri2 = new TrianguloR(v2, v3, v4, color);
            tri2.dibujar(raster);
        } else if ((p1.x > p2.x) && (p1.y > p2.y)) {
            Vertex2D v1 = new Vertex2D(p1.x, p1.y, color.getRGB());
            Vertex2D v2 = new Vertex2D(p1.x - d, p1.y, color.getRGB());
            Vertex2D v3 = new Vertex2D(p1.x, p1.y - d, color.getRGB());
            Vertex2D v4 = new Vertex2D(p2.x, p2.y, color.getRGB());
            TrianguloR tri = new TrianguloR(v1, v2, v3, color);
            tri.dibujar(raster);
            TrianguloR tri2 = new TrianguloR(v2, v3, v4, color);
            tri2.dibujar(raster);
        } else if ((p1.x > p2.x) && (p1.y < p2.y)) {
            Vertex2D v1 = new Vertex2D(p1.x, p1.y, color.getRGB());
            Vertex2D v2 = new Vertex2D(p1.x - d, p1.y, color.getRGB());
            Vertex2D v3 = new Vertex2D(p1.x, p1.y + d, color.getRGB());
            Vertex2D v4 = new Vertex2D(p2.x, p2.y, color.getRGB());
            TrianguloR tri = new TrianguloR(v1, v2, v3, color);
            tri.dibujar(raster);
            TrianguloR tri2 = new TrianguloR(v2, v3, v4, color);
            tri2.dibujar(raster);
        }
    }

    public int Obteneropcion() {
        int opc = 0;
        if (this.jRadioButton1.isSelected()) {
            opc = 1;
        } else if (this.jRadioButton2.isSelected()) {
            opc = 2;
        }else if (this.jRadioButton4.isSelected()) {
            opc = 4;
        } else if (this.jRadioButton5.isSelected()) {
            opc = 5;
        }
        return opc;
    }

    public void clear() {
        int s = raster.size();
        for (int i = 0; i < s; i++) {
            raster.pixel[i] ^= 0x00ffffff;
        }
        super.repaint();
        return;
    }

    public void Circulo(Point p1, Point p2, int r, Color color) {
        int pix = color.getRGB();
        double x2, y2;
        double angulo = 0;
        do {
            do {
                x2 = p1.x + r * Math.cos(angulo);
                y2 = p1.y + r * Math.sin(angulo);
                angulo += 0.005;
                raster.setPixel(pix, (int) x2, (int) y2);
            } while (angulo < 6.28);
            r--;
            angulo = 0;
        } while (r != 0);
    }

    public void Elipse(Point p1, Point p2,double r, Color color) {
        double a, angulo, x3, y3, dis, teta;
        int xr, altura = (int)(r/2);
        int pix = color.getRGB();
        a = Math.abs(p2.x - p1.x);
        xr = p1.x + (int) (a * Math.cos(0));
        dis = Math.sqrt(Math.pow(p2.x - xr, 2));
        teta = Math.asin((dis / 2) / a);
        teta = 2 * teta;
        do {
            for (angulo = 0; angulo <= 360; angulo++) {
                x3 = p1.x + a * Math.cos(angulo + teta);
                y3 = p1.y + altura * Math.sin(angulo);
                p2.x = (int) x3;
                p2.y = (int) y3;
                raster.setPixel(pix, (int) Math.round(x3), (int) Math.round(y3));
                dibujarLinea(p1, p2, color);
            }
            a--;
            altura--;

        } while (a != 0 && altura != 0);
    }

    public double Rad(Point p1, Point p2) {
        double radio;
        radio = (Math.sqrt(((p2.x - p1.x) * (p2.x - p1.x)) + ((p2.y - p1.y) * (p2.y - p1.y))));
        return radio;
    }

    public void PizarraMouseClicked(java.awt.event.MouseEvent evt) {
        try {
            switch (Obteneropcion()) {
                case 1:
                    if (b1) {
                        p1.x = evt.getX();
                        p1.y = evt.getY();
                        b1 = false;
                    } else {
                        p2.x = evt.getX();
                        p2.y = evt.getY();
                        dibujarLinea(p1, p2, Color.BLUE);
                        b1 = true;
                        Point ma[];
                        ma = new Point[2];
                        ma[0] = p1;
                        ma[1] = p2;
                        arregloF.add(new Figura(ma, 1, 0, Color.BLUE));
                        contadorlinea++;
                        this.jComboBox1.addItem("Linea " + contadorlinea);
                    }
                    break;
                case 2:
                    if (b1) {
                        p1.x = evt.getX();
                        p1.y = evt.getY();
                        b1 = false;
                    } else {
                        p2.x = evt.getX();
                        p2.y = evt.getY();
                        Circulo(p1, p2, (int) Rad(p1, p2), Color.RED);
                        Point ma[];
                        ma = new Point[2];
                        ma[0] = p1;
                        ma[1] = p2;
                        arregloF.add(new Figura(ma, 2, Rad(p1, p2), Color.RED));
                        contadorcirculo++;
                        this.jComboBox1.addItem("Circulo " + contadorcirculo);
                        b1 = true;
                    }
                    break;
                case 3:
                    if (b1) {
                        p1.x = evt.getX();
                        p1.y = evt.getY();
                        b1 = false;
                    } else {
                        p2.x = evt.getX();
                        p2.y = evt.getY();
                        Elipse(p1, p2,Rad(p1, p2),Color.GREEN);
                        b1 = true;
                        Point ma[];
                        ma = new Point[2];
                        ma[0] = p1;
                        ma[1] = p2;
                        arregloF.add(new Figura(ma, 3, 0, Color.GREEN));
                        contadorelipse++;
                        this.jComboBox1.addItem("Elipse " + contadorelipse);
                        b1 = b2 = true;
                    }
                    break;
                case 4:
                    if (b1 && b2) {
                        p1.x = evt.getX();
                        p1.y = evt.getY();
                        b1 = false;
                    } else if (!b1 && b2) {
                        p2.x = evt.getX();
                        p2.y = evt.getY();
                        b2 = false;
                    } else if (!b1 && !b2) {
                        p3.x = evt.getX();
                        p3.y = evt.getY();
                        Triangulo(p1, p2, p3, Color.GRAY);
                        Point ma[];
                        ma = new Point[3];
                        ma[0] = p1;
                        ma[1] = p2;
                        ma[2] = p3;
                        arregloF.add(new Figura(ma, 4, 0, Color.GRAY));
                        contadortriangulo++;
                        this.jComboBox1.addItem("Triangulo " + contadortriangulo);
                        b1 = b2 = true;
                    }
                    break;
                case 5:
                    if (b1) {
                        p1.x = evt.getX();
                        p1.y = evt.getY();
                        b1 = false;
                    } else {
                        p2.x = evt.getX();
                        p2.y = evt.getY();
                        Cuadrado(p1, p2, Color.GREEN);
                        Point ma[];
                        ma = new Point[2];
                        ma[0] = p1;
                        ma[1] = p2;
                        arregloF.add(new Figura(ma, 5, 0, Color.GREEN));
                        contadorcuadrado++;
                        this.jComboBox1.addItem("Cuadrado " + contadorcuadrado);
                        b1 = true;
                    }
                default:
                    break;
            }
        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
